name: Update NECHR

on:
  push:
    paths:
      - 'latest.7z'

jobs:
  trigger_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/cbdb-project/named-entities-for-premodern-chinese-history-research/actions/workflows/57137209/dispatches \
          -d '{"ref": "main"}'

      - name: Check Access to GH_TOKEN
        run: |
          if [[ -z "${{ secrets.GH_TOKEN }}" ]]; then
            echo "GH_TOKEN is not accessible."
            exit 1
          else
            echo "GH_TOKEN is accessible."
          fi
